/**
 * LandingKnowledgeShowcase — Bridges marketing site to public knowledge pages.
 * Shows curated examples of insights, patterns, frameworks to demonstrate value.
 */
import { motion } from "framer-motion";
import { ArrowRight, Brain, Lightbulb, Network, Zap, BookOpen, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";
import patternExtractionDiagram from "@/assets/diagrams/pattern-extraction-dark.png";
import monetizeDiagram from "@/assets/diagrams/monetize-flow-dark.png";

const SHOWCASE_ITEMS = [
  {
    icon: Lightbulb,
    category: "Insight",
    title: "The Attention Arbitrage Window",
    description: "Most creators compete for attention in saturated channels. The real opportunity is in underpriced attention markets that match your expertise depth.",
    link: "/insights",
    color: "text-[hsl(var(--gold-oxide))]",
    bg: "bg-[hsl(var(--gold-oxide)/0.05)]",
    border: "border-[hsl(var(--gold-oxide)/0.15)]",
  },
  {
    icon: Network,
    category: "Framework",
    title: "Decision Stack Architecture",
    description: "Layer your decisions: Identity → Strategy → Tactics → Execution. Each layer constrains the next, eliminating 80% of options before you think.",
    link: "/patterns",
    color: "text-primary",
    bg: "bg-primary/5",
    border: "border-primary/15",
  },
  {
    icon: Target,
    category: "Pattern",
    title: "The Expertise Compression Loop",
    description: "Extract → Structure → Teach → Monetize → Extract deeper. Each cycle compounds your authority and creates asymmetric knowledge advantages.",
    link: "/formulas",
    color: "text-[hsl(var(--gold-oxide))]",
    bg: "bg-[hsl(var(--gold-oxide)/0.05)]",
    border: "border-[hsl(var(--gold-oxide)/0.15)]",
  },
  {
    icon: Zap,
    category: "Formula",
    title: "Content ROI Multiplier",
    description: "One long-form piece → 12 micro-content pieces → 3 lead magnets → 1 course module. Systematic extraction beats random creation 47x.",
    link: "/formulas",
    color: "text-primary",
    bg: "bg-primary/5",
    border: "border-primary/15",
  },
];

export function LandingKnowledgeShowcase() {
  const navigate = useNavigate();

  return (
    <section className="py-20 sm:py-28 px-5 sm:px-6 relative">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-[hsl(var(--gold-oxide)/0.2)] bg-[hsl(var(--gold-oxide)/0.05)] mb-4">
            <Brain className="h-3 w-3 text-[hsl(var(--gold-oxide))]" />
            <span className="text-micro font-mono tracking-widest text-[hsl(var(--gold-oxide))]">
              KNOWLEDGE BASE
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-foreground mb-3">
            Real knowledge, extracted by AI
          </h2>
          <p className="text-sm text-muted-foreground max-w-lg mx-auto">
            Browse insights, patterns, and frameworks generated by our extraction engine.
            Every piece is an atomic knowledge unit — ready to apply.
          </p>
        </motion.div>

        {/* Cards Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
          {SHOWCASE_ITEMS.map((item, i) => {
            const Icon = item.icon;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                onClick={() => navigate(item.link)}
                className={cn(
                  "group cursor-pointer rounded-xl border p-5 transition-all duration-200",
                  "hover:shadow-lg hover:-translate-y-0.5",
                  item.bg, item.border,
                )}
              >
                <div className="flex items-start gap-3">
                  <div className={cn(
                    "h-8 w-8 rounded-lg flex items-center justify-center shrink-0",
                    item.bg, "border", item.border,
                  )}>
                    <Icon className={cn("h-4 w-4", item.color)} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className={cn("text-nano font-mono tracking-widest uppercase", item.color)}>
                        {item.category}
                      </span>
                    </div>
                    <h3 className="text-sm font-semibold text-foreground mb-1.5 group-hover:text-primary transition-colors">
                      {item.title}
                    </h3>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      {item.description}
                    </p>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Pattern Extraction Diagram */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-12"
        >
          <div className="relative rounded-xl overflow-hidden border border-border/30 bg-[hsl(var(--obsidian))]">
            <img
              src={patternExtractionDiagram}
              alt="Pattern Extraction: Transcripts, Voice Notes, Text Data → Recurring Ideas, Decision Rules, Frameworks, Content Seeds, Product Insights → Atomic Knowledge Graph"
              className="w-full h-auto"
              loading="lazy"
            />
            <div className="absolute inset-0 rounded-xl ring-1 ring-inset ring-[hsl(var(--gold-oxide)/0.08)] pointer-events-none" />
          </div>
        </motion.div>

        {/* Monetize Flow Diagram */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mb-10"
        >
          <div className="text-center mb-6">
            <span className="text-micro font-mono tracking-[0.25em] text-[hsl(var(--gold-oxide)/0.6)]">
              MONETIZATION PIPELINE
            </span>
          </div>
          <div className="relative rounded-xl overflow-hidden border border-border/30 bg-[hsl(var(--obsidian))]">
            <img
              src={monetizeDiagram}
              alt="Monetizing Intelligence: Expertise → Structured Insights → Digital Assets → Content Products → Recurring Revenue (Subscriptions, Memberships, Licensing)"
              className="w-full h-auto"
              loading="lazy"
            />
            <div className="absolute inset-0 rounded-xl ring-1 ring-inset ring-[hsl(var(--gold-oxide)/0.08)] pointer-events-none" />
          </div>
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="flex justify-center"
        >
          <Button
            variant="outline"
            onClick={() => navigate("/insights")}
            className="gap-2 text-xs border-[hsl(var(--gold-oxide)/0.3)] text-[hsl(var(--gold-oxide))] hover:bg-[hsl(var(--gold-oxide)/0.05)]"
          >
            <BookOpen className="h-3.5 w-3.5" />
            Explore Knowledge Base
            <ArrowRight className="h-3 w-3" />
          </Button>
        </motion.div>
      </div>
    </section>
  );
}
