import { SEOHead } from "@/components/SEOHead";
import { Link } from "react-router-dom";

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-14">
      <SEOHead
        title="Terms of Service — AI-IDEI"
        description="Terms and conditions for using the AI-IDEI Knowledge OS platform."
        canonical="https://ai-idei-os.lovable.app/terms"
      />

      <h1 className="text-2xl sm:text-3xl font-serif font-bold mb-6">Terms of Service</h1>
      <p className="text-xs text-muted-foreground mb-8">Last updated: March 10, 2026</p>

      <article className="prose-custom space-y-6 text-sm leading-relaxed text-foreground/90">
        <section>
          <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the AI-IDEI Knowledge OS platform ("Service"), you agree to be bound by these Terms of Service.
            If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">2. Description of Service</h2>
          <p>
            AI-IDEI is an AI-powered knowledge extraction and capitalization platform. It transforms raw content
            (audio, video, text) into structured knowledge units called "neurons" and generates reusable digital assets ("artifacts").
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">3. User Accounts</h2>
          <p>
            You must provide accurate information when creating an account. You are responsible for maintaining the
            confidentiality of your credentials and for all activities under your account.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">4. Content Ownership</h2>
          <p>
            You retain full ownership of all content you upload ("User Content"). By uploading, you grant AI-IDEI a
            limited license to process your content for the purpose of delivering the Service. We do not sell, share,
            or publicly expose your private content without your explicit consent.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">5. Credits System (NEURONS)</h2>
          <p>
            The platform uses a credit-based system called NEURONS to meter AI service consumption. Credits are
            non-refundable once consumed. Unused credits remain in your account indefinitely unless otherwise stated.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Upload illegal, harmful, or infringing content</li>
            <li>Attempt to reverse-engineer, exploit, or disrupt the Service</li>
            <li>Use automated systems to scrape or extract data beyond intended use</li>
            <li>Violate the intellectual property rights of others</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">7. AI-Generated Content</h2>
          <p>
            Outputs generated by AI services are provided "as-is." While we strive for accuracy, AI-generated
            content may contain errors. You are responsible for reviewing and validating all outputs before use.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">8. Limitation of Liability</h2>
          <p>
            AI-IDEI is provided "as-is" without warranties of any kind. We are not liable for any indirect,
            incidental, or consequential damages arising from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">9. Termination</h2>
          <p>
            We reserve the right to suspend or terminate accounts that violate these terms. You may delete your
            account at any time by contacting support.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">10. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes constitutes
            acceptance of the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">11. Contact</h2>
          <p>
            For questions about these Terms, please use the{" "}
            <Link to="/feedback" className="text-primary hover:underline">feedback form</Link>.
          </p>
        </section>
      </article>
    </div>
  );
}
