INSERT INTO service_registry (id,name,service_level,category,intent,neurons_cost_min,neurons_cost_max,score_tier,complexity,output_type,domain,is_active,position) VALUES
(gen_random_uuid(),'In-Group Invitation We-Statement Relationships Opening Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,201),
(gen_random_uuid(),'Erosion Stop Prediction Money Objection Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,202),
(gen_random_uuid(),'Option Set Try-This Command Productivity CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,203),
(gen_random_uuid(),'Before-After Identity Contrast Identity Reframe Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,204),
(gen_random_uuid(),'Danger Proximity If-You-Don''t Prediction Health CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,205),
(gen_random_uuid(),'Want Signal Statement Confidence Promise Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,206),
(gen_random_uuid(),'Insider Credential Boundary Statement Fitness Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,207),
(gen_random_uuid(),'Curiosity Gap Contrast Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,208),
(gen_random_uuid(),'Fear Amplification Question Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,209),
(gen_random_uuid(),'Status Loss Statement Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,210),
(gen_random_uuid(),'Desire Projection Opening Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,211),
(gen_random_uuid(),'Authority Collapse Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,212),
(gen_random_uuid(),'Identity Disruption Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,213),
(gen_random_uuid(),'Urgency Spike Opening Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,214),
(gen_random_uuid(),'Hidden Cost Reveal Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,215),
(gen_random_uuid(),'Outcome Delay Warning Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,216),
(gen_random_uuid(),'Binary Decision Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,217),
(gen_random_uuid(),'Time Scarcity Opening Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,218),
(gen_random_uuid(),'False Belief Breakdown Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,219),
(gen_random_uuid(),'Expectation Reversal Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,220),
(gen_random_uuid(),'Specific Pain Naming Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,221),
(gen_random_uuid(),'Future Regret Projection Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,222),
(gen_random_uuid(),'Immediate Consequence Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,223),
(gen_random_uuid(),'Social Comparison Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,224),
(gen_random_uuid(),'Uncomfortable Truth Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,225),
(gen_random_uuid(),'Internal Conflict Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,226),
(gen_random_uuid(),'Micro-Insight Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,227),
(gen_random_uuid(),'"How to Escape [Pain] Fast" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,228),
(gen_random_uuid(),'"Why [Effort] Fails" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,229),
(gen_random_uuid(),'"What Nobody Told You About [X]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,230),
(gen_random_uuid(),'"Stop Trusting [X]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,231),
(gen_random_uuid(),'"This One Shift Changes [Outcome]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,232),
(gen_random_uuid(),'"You''re Doing [X] Wrong" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,233),
(gen_random_uuid(),'"Before You Try [X], Read This" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,234),
(gen_random_uuid(),'"The Hidden Reason Behind [Failure]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,235),
(gen_random_uuid(),'"If You Still Believe [X], You''re Losing" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,236),
(gen_random_uuid(),'"This Is Why You''re Stuck in [State]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,237),
(gen_random_uuid(),'"You Don''t Need More [X]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,238),
(gen_random_uuid(),'"The Fastest Way to Fix [X]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,239),
(gen_random_uuid(),'"Most People Ignore This About [X]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,240),
(gen_random_uuid(),'"You Can''t Scale [X] Like This" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,241),
(gen_random_uuid(),'"This Is Killing Your [Outcome]" Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,242),
(gen_random_uuid(),'Click-to-Transform CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,243),
(gen_random_uuid(),'Instant Access CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,244),
(gen_random_uuid(),'Risk-Free Action CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,245),
(gen_random_uuid(),'One-Click Upgrade CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,246),
(gen_random_uuid(),'Start Before Ready CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,247),
(gen_random_uuid(),'Skip the Waiting CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,248),
(gen_random_uuid(),'Claim Immediate Result CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,249),
(gen_random_uuid(),'Execute Now CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,250),
(gen_random_uuid(),'Unlock Faster Outcome CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,251),
(gen_random_uuid(),'Test It Yourself CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,252),
(gen_random_uuid(),'Take Control Now CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,253),
(gen_random_uuid(),'Remove Friction CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,254),
(gen_random_uuid(),'Activate Change CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,255),
(gen_random_uuid(),'Enter the System CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,256),
(gen_random_uuid(),'Get the Edge CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,257),
(gen_random_uuid(),'Stacked Value Justification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,258),
(gen_random_uuid(),'Invisible Benefit Highlight Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,259),
(gen_random_uuid(),'Outcome Compression Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,260),
(gen_random_uuid(),'Effort Elimination Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,261),
(gen_random_uuid(),'Speed Advantage Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,262),
(gen_random_uuid(),'Certainty Framing Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,263),
(gen_random_uuid(),'Guaranteed Shift Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,264),
(gen_random_uuid(),'Low Risk Entry Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,265),
(gen_random_uuid(),'Immediate ROI Framing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,266),
(gen_random_uuid(),'High Leverage Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,267),
(gen_random_uuid(),'Simplification Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,268),
(gen_random_uuid(),'Priority Access Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,269),
(gen_random_uuid(),'Direct Result Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,270),
(gen_random_uuid(),'Shortcut Value Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,271),
(gen_random_uuid(),'Asymmetric Value Offer Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,272),
(gen_random_uuid(),'"I Don''t Have Time" Collapse Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,273),
(gen_random_uuid(),'"I Need More Info" Collapse Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,274),
(gen_random_uuid(),'"This Is Too Risky" Neutralization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,275),
(gen_random_uuid(),'"I''ll Do It Later" Breaker Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,276),
(gen_random_uuid(),'"I Tried This Before" Reframe Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,277),
(gen_random_uuid(),'"It Won''t Work For Me" Disarm Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,278),
(gen_random_uuid(),'"I Need Approval" Collapse Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,279),
(gen_random_uuid(),'"I''m Not Ready" Flip Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,280),
(gen_random_uuid(),'"I Don''t Trust This" Proof Injection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,281),
(gen_random_uuid(),'"I Can''t Afford It" Value Reframe Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,282),
(gen_random_uuid(),'Origin Shift Story Opening Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,283),
(gen_random_uuid(),'Moment of Failure Narrative Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,284),
(gen_random_uuid(),'Unexpected Breakthrough Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,285),
(gen_random_uuid(),'Turning Point Compression Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,286),
(gen_random_uuid(),'Identity Rebuild Narrative Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,287),
(gen_random_uuid(),'Pain Recognition Story Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,288),
(gen_random_uuid(),'Old vs New Self Contrast Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,289),
(gen_random_uuid(),'Discovery Moment Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,290),
(gen_random_uuid(),'Internal Realization Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,291),
(gen_random_uuid(),'External Trigger Story Line Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,292),
(gen_random_uuid(),'Hook - Tension - Release Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,293),
(gen_random_uuid(),'Problem - Escalation - Exit Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,294),
(gen_random_uuid(),'Insight - Application - Result Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,295),
(gen_random_uuid(),'Trigger - Response - Outcome Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,296),
(gen_random_uuid(),'Claim - Breakdown - Replacement Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,297),
(gen_random_uuid(),'Observation - Pattern - Prediction Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,298),
(gen_random_uuid(),'Conflict - Decision - Result Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,299),
(gen_random_uuid(),'Belief - Disruption - Rebuild Structure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,300)
ON CONFLICT DO NOTHING;