INSERT INTO service_registry (id,name,service_level,category,intent,neurons_cost_min,neurons_cost_max,score_tier,complexity,output_type,domain,is_active,position) VALUES
(gen_random_uuid(),'Monetization Friction Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,401),
(gen_random_uuid(),'Customer Lifetime Value Expansion Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,402),
(gen_random_uuid(),'Acquisition Cost Recovery Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,403),
(gen_random_uuid(),'Revenue Leak Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,404),
(gen_random_uuid(),'Profit Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,405),
(gen_random_uuid(),'Offer Profitability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,406),
(gen_random_uuid(),'Break-Even Acceleration Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,407),
(gen_random_uuid(),'Task Decomposition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,408),
(gen_random_uuid(),'Agent Role Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,409),
(gen_random_uuid(),'Prompt Precision Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,410),
(gen_random_uuid(),'Input → Output Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,411),
(gen_random_uuid(),'Automation Trigger Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,412),
(gen_random_uuid(),'Workflow Simplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,413),
(gen_random_uuid(),'Execution Loop Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,414),
(gen_random_uuid(),'System Dependency Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,415),
(gen_random_uuid(),'Parallel Task Distribution Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,416),
(gen_random_uuid(),'Sequential Execution Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,417),
(gen_random_uuid(),'Failure Recovery Path Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,418),
(gen_random_uuid(),'Output Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,419),
(gen_random_uuid(),'Memory Injection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,420),
(gen_random_uuid(),'Agent Instruction Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,421),
(gen_random_uuid(),'Process Replication Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,422),
(gen_random_uuid(),'AXA — CONTENT SYSTEM','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,423),
(gen_random_uuid(),'Content Topic Extraction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,424),
(gen_random_uuid(),'Content Angle Differentiation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,425),
(gen_random_uuid(),'Content Series Structuring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,426),
(gen_random_uuid(),'Content Distribution Split Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,427),
(gen_random_uuid(),'Content Repurposing Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,428),
(gen_random_uuid(),'Content Priority Matrix Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,429),
(gen_random_uuid(),'Content Lifecycle Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,430),
(gen_random_uuid(),'Content Signal Amplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,431),
(gen_random_uuid(),'Content Feedback Loop Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,432),
(gen_random_uuid(),'Content Output Density Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,433),
(gen_random_uuid(),'Content Relevance Scoring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,434),
(gen_random_uuid(),'Content Direction Alignment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,435),
(gen_random_uuid(),'Content Theme Consolidation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,436),
(gen_random_uuid(),'Content Expansion Path Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,437),
(gen_random_uuid(),'Content Saturation Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,438),
(gen_random_uuid(),'Audience Segmentation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,439),
(gen_random_uuid(),'Pain Point Isolation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,440),
(gen_random_uuid(),'Desire Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,441),
(gen_random_uuid(),'Belief System Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,442),
(gen_random_uuid(),'Market Awareness Level Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,443),
(gen_random_uuid(),'Objection Pattern Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,444),
(gen_random_uuid(),'Customer Journey Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,445),
(gen_random_uuid(),'Trust Signal Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,446),
(gen_random_uuid(),'Status Hierarchy Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,447),
(gen_random_uuid(),'Behavior Pattern Recognition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,448),
(gen_random_uuid(),'Decision Trigger Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,449),
(gen_random_uuid(),'Emotional Driver Isolation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,450),
(gen_random_uuid(),'Market Gap Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,451),
(gen_random_uuid(),'Audience Intent Classification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,452),
(gen_random_uuid(),'Perception Shift Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,453),
(gen_random_uuid(),'Identity Core Extraction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,454),
(gen_random_uuid(),'Authority Vector Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,455),
(gen_random_uuid(),'Positioning Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,456),
(gen_random_uuid(),'Niche Narrowing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,457),
(gen_random_uuid(),'Narrative Alignment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,458),
(gen_random_uuid(),'Differentiation Axis Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,459),
(gen_random_uuid(),'Reputation Signal Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,460),
(gen_random_uuid(),'Brand Voice Structuring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,461),
(gen_random_uuid(),'Perception Control Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,462),
(gen_random_uuid(),'Identity Expansion Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,463),
(gen_random_uuid(),'Authority Proof Structuring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,464),
(gen_random_uuid(),'Personal Doctrine Extraction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,465),
(gen_random_uuid(),'Brand Consistency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,466),
(gen_random_uuid(),'Influence Vector Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,467),
(gen_random_uuid(),'Identity Reinforcement Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,468),
(gen_random_uuid(),'Task Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,469),
(gen_random_uuid(),'Time Allocation Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,470),
(gen_random_uuid(),'Execution Sequence Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,471),
(gen_random_uuid(),'Focus Block Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,472),
(gen_random_uuid(),'Distraction Elimination Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,473),
(gen_random_uuid(),'Output Maximization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,474),
(gen_random_uuid(),'Effort vs Output Ratio Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,475),
(gen_random_uuid(),'Workload Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,476),
(gen_random_uuid(),'Execution Friction Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,477),
(gen_random_uuid(),'Task Batching Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,478),
(gen_random_uuid(),'Context Switching Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,479),
(gen_random_uuid(),'Deadline Structuring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,480),
(gen_random_uuid(),'Execution Momentum Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,481),
(gen_random_uuid(),'Completion Acceleration Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,482),
(gen_random_uuid(),'Energy Allocation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,483),
(gen_random_uuid(),'Signal vs Noise Separation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,484),
(gen_random_uuid(),'KPI Selection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,485),
(gen_random_uuid(),'Metric Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,486),
(gen_random_uuid(),'Conversion Analysis Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,487),
(gen_random_uuid(),'Performance Attribution Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,488),
(gen_random_uuid(),'Trend Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,489),
(gen_random_uuid(),'Data Simplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,490),
(gen_random_uuid(),'Feedback Extraction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,491),
(gen_random_uuid(),'Insight Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,492),
(gen_random_uuid(),'Anomaly Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,493),
(gen_random_uuid(),'Growth Rate Calculation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,494),
(gen_random_uuid(),'Drop-Off Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,495),
(gen_random_uuid(),'Pattern Recognition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,496),
(gen_random_uuid(),'Optimization Direction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,497),
(gen_random_uuid(),'Outcome Measurement Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,498),
(gen_random_uuid(),'System Boundary Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,499),
(gen_random_uuid(),'Input Constraint Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,500),
(gen_random_uuid(),'Output Standardization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,501),
(gen_random_uuid(),'Dependency Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,502),
(gen_random_uuid(),'Complexity Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,503),
(gen_random_uuid(),'Scalability Path Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,504),
(gen_random_uuid(),'Modularization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,505),
(gen_random_uuid(),'System Abstraction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,506),
(gen_random_uuid(),'Control Point Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,507),
(gen_random_uuid(),'Failure Point Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,508),
(gen_random_uuid(),'Redundancy Elimination Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,509),
(gen_random_uuid(),'System Efficiency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,510),
(gen_random_uuid(),'Throughput Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,511),
(gen_random_uuid(),'Feedback Injection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,512),
(gen_random_uuid(),'Self-Improvement Loop Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,513),
(gen_random_uuid(),'Lead Qualification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,514),
(gen_random_uuid(),'Sales Objection Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,515),
(gen_random_uuid(),'Closing Path Selection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,516),
(gen_random_uuid(),'Conversion Friction Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,517),
(gen_random_uuid(),'Buyer Intent Scoring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,518),
(gen_random_uuid(),'Sales Script Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','sales',true,519),
(gen_random_uuid(),'Offer Fit Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,520),
(gen_random_uuid(),'Lead Temperature Classification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,521),
(gen_random_uuid(),'Sales Angle Selection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','sales',true,522),
(gen_random_uuid(),'Decision Acceleration Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,523),
(gen_random_uuid(),'Buyer Resistance Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,524),
(gen_random_uuid(),'Closing Timing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,525),
(gen_random_uuid(),'Conversion Leak Isolation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,526),
(gen_random_uuid(),'Sales Priority Routing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','sales',true,527),
(gen_random_uuid(),'Deal Probability Estimation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,528),
(gen_random_uuid(),'Entry Point Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,529),
(gen_random_uuid(),'Drop-Off Stage Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,530),
(gen_random_uuid(),'Funnel Simplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,531),
(gen_random_uuid(),'Conversion Step Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,532),
(gen_random_uuid(),'Multi-Step Flow Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,533),
(gen_random_uuid(),'Funnel Dependency Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,534),
(gen_random_uuid(),'Critical Path Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,535),
(gen_random_uuid(),'Flow Continuity Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,536),
(gen_random_uuid(),'Entry Barrier Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,537),
(gen_random_uuid(),'Exit Point Capture Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,538),
(gen_random_uuid(),'Conversion Path Clarity Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,539),
(gen_random_uuid(),'Step Elimination Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,540),
(gen_random_uuid(),'AXA — GROWTH / DISTRIBUTION','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,541),
(gen_random_uuid(),'Channel Selection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,542),
(gen_random_uuid(),'Traffic Source Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,543),
(gen_random_uuid(),'Distribution Leverage Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,544),
(gen_random_uuid(),'Growth Constraint Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,545),
(gen_random_uuid(),'Audience Expansion Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,546),
(gen_random_uuid(),'Virality Trigger Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,547),
(gen_random_uuid(),'Content Distribution Timing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,548),
(gen_random_uuid(),'Growth Rate Acceleration Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,549),
(gen_random_uuid(),'Audience Penetration Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,550),
(gen_random_uuid(),'Platform Fit Evaluation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,551),
(gen_random_uuid(),'Reach Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,552),
(gen_random_uuid(),'Traffic Conversion Matching Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,553),
(gen_random_uuid(),'Growth Opportunity Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,554),
(gen_random_uuid(),'Distribution Efficiency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,555),
(gen_random_uuid(),'Signal Amplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,556),
(gen_random_uuid(),'Community Entry Filter Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,557),
(gen_random_uuid(),'Engagement Trigger Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,558),
(gen_random_uuid(),'Retention Loop Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,559),
(gen_random_uuid(),'Contribution Incentive Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,560),
(gen_random_uuid(),'Member Value Alignment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,561),
(gen_random_uuid(),'Community Growth Balance Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,562),
(gen_random_uuid(),'Network Density Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,563),
(gen_random_uuid(),'Participation Activation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,564),
(gen_random_uuid(),'Trust Building Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,565),
(gen_random_uuid(),'Status Ladder Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,566),
(gen_random_uuid(),'Community Health Measurement Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,567),
(gen_random_uuid(),'Exit Risk Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,568),
(gen_random_uuid(),'Core Member Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,569),
(gen_random_uuid(),'Influence Distribution Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,570),
(gen_random_uuid(),'Interaction Frequency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,571),
(gen_random_uuid(),'Competitor Position Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,572),
(gen_random_uuid(),'Market Saturation Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,573),
(gen_random_uuid(),'Differentiation Gap Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,574),
(gen_random_uuid(),'Competitive Advantage Isolation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,575),
(gen_random_uuid(),'Market Entry Strategy Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,576),
(gen_random_uuid(),'Positioning Conflict Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,577),
(gen_random_uuid(),'Demand Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,578),
(gen_random_uuid(),'Category Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,579),
(gen_random_uuid(),'Market Narrative Control Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,580),
(gen_random_uuid(),'Competitive Weakness Exposure Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,581),
(gen_random_uuid(),'Opportunity Window Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,582),
(gen_random_uuid(),'Price Positioning Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,583),
(gen_random_uuid(),'Market Expansion Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,584),
(gen_random_uuid(),'Dominance Strategy Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,585),
(gen_random_uuid(),'Niche Defense Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,586),
(gen_random_uuid(),'Cash Flow Projection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,587),
(gen_random_uuid(),'Expense Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,588),
(gen_random_uuid(),'Budget Allocation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,589),
(gen_random_uuid(),'Profit Margin Calculation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,590),
(gen_random_uuid(),'Cost Reduction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,591),
(gen_random_uuid(),'Revenue Forecast Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,592),
(gen_random_uuid(),'Financial Risk Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,593),
(gen_random_uuid(),'Break-Even Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,594),
(gen_random_uuid(),'Capital Efficiency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,595),
(gen_random_uuid(),'Investment Allocation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,596),
(gen_random_uuid(),'Liquidity Management Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,597),
(gen_random_uuid(),'Financial Stability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,598),
(gen_random_uuid(),'Cost vs Value Analysis Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,599),
(gen_random_uuid(),'Revenue Consistency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,600)
ON CONFLICT DO NOTHING;