INSERT INTO service_registry (id,name,service_level,category,intent,neurons_cost_min,neurons_cost_max,score_tier,complexity,output_type,domain,is_active,position) VALUES
(gen_random_uuid(),'Infrastructure Optimization System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1401),
(gen_random_uuid(),'System → Scale Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1402),
(gen_random_uuid(),'Data → Insight Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1403),
(gen_random_uuid(),'Feedback Integration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1404),
(gen_random_uuid(),'Performance Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1405),
(gen_random_uuid(),'Data → Decision System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1406),
(gen_random_uuid(),'Insight → Action Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1407),
(gen_random_uuid(),'Feedback Loop System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1408),
(gen_random_uuid(),'Performance Tracking System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1409),
(gen_random_uuid(),'Data Consistency Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1410),
(gen_random_uuid(),'Optimization Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1411),
(gen_random_uuid(),'Insight → Growth Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1412),
(gen_random_uuid(),'Agent Deployment Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1413),
(gen_random_uuid(),'Agent Coordination Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1414),
(gen_random_uuid(),'Agent Efficiency System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1415),
(gen_random_uuid(),'Workflow Automation Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1416),
(gen_random_uuid(),'Agent Scaling System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1417),
(gen_random_uuid(),'Automation Consistency Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1418),
(gen_random_uuid(),'Agent → Decision System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1419),
(gen_random_uuid(),'Automation → Revenue Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1420),
(gen_random_uuid(),'Knowledge → Action Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1421),
(gen_random_uuid(),'Skill Development System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1422),
(gen_random_uuid(),'Learning Acceleration Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1423),
(gen_random_uuid(),'Understanding → Execution System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1424),
(gen_random_uuid(),'Cognitive Upgrade Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1425),
(gen_random_uuid(),'Learning → Output Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1426),
(gen_random_uuid(),'Skill Consistency System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1427),
(gen_random_uuid(),'Knowledge Application Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1428),
(gen_random_uuid(),'Learning Loop System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1429),
(gen_random_uuid(),'Transformation Acceleration Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1430),
(gen_random_uuid(),'Decision → Outcome System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1431),
(gen_random_uuid(),'Control → Execution Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1432),
(gen_random_uuid(),'Priority → Result System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1433),
(gen_random_uuid(),'Decision Stability System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1434),
(gen_random_uuid(),'Control Alignment Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1435),
(gen_random_uuid(),'Decision → Revenue System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1436),
(gen_random_uuid(),'Execution Control System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1437),
(gen_random_uuid(),'Decision Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1438),
(gen_random_uuid(),'Outcome Alignment System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1439),
(gen_random_uuid(),'Control Consistency System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1440),
(gen_random_uuid(),'Execution Speed System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1441),
(gen_random_uuid(),'Time → Output Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1442),
(gen_random_uuid(),'Speed Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1443),
(gen_random_uuid(),'Time Compression System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1444),
(gen_random_uuid(),'Execution Acceleration Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1445),
(gen_random_uuid(),'Response Speed System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1446),
(gen_random_uuid(),'Time Efficiency Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1447),
(gen_random_uuid(),'Delivery Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1448),
(gen_random_uuid(),'Time → Revenue System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1449),
(gen_random_uuid(),'Speed → Conversion Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1450),
(gen_random_uuid(),'2) PROMPT — MMS AUTO-COMPOSER ENGINE','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1451),
(gen_random_uuid(),'id: MMS_AUTO_COMPOSER_ENGINE','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1452),
(gen_random_uuid(),'type: generation_system','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1453),
(gen_random_uuid(),'name: intent_mapping','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1454),
(gen_random_uuid(),'name: DAG_construction','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1455),
(gen_random_uuid(),'name: score_optimization','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1456),
(gen_random_uuid(),'MMS_181 — Cold Outreach Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1457),
(gen_random_uuid(),'name: Cold Outreach Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1458),
(gen_random_uuid(),'MMS_193 — Click-to-Action Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1459),
(gen_random_uuid(),'name: Click-to-Action Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1460),
(gen_random_uuid(),'MMS_235 — Subscription Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1461),
(gen_random_uuid(),'name: Subscription Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1462),
(gen_random_uuid(),'reinvestment loop','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1463),
(gen_random_uuid(),'name: loop_injection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1464),
(gen_random_uuid(),'name: output_definition','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1465),
(gen_random_uuid(),'feedback loop','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1466),
(gen_random_uuid(),'Style Clarity Evaluation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1467),
(gen_random_uuid(),'Tone Classification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1468),
(gen_random_uuid(),'Lexical Density Measurement Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1469),
(gen_random_uuid(),'Sentence Complexity Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1470),
(gen_random_uuid(),'Emotional Signal Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1471),
(gen_random_uuid(),'Rhetorical Device Identification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1472),
(gen_random_uuid(),'Audience Fit Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1473),
(gen_random_uuid(),'Coherence Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1474),
(gen_random_uuid(),'Redundancy Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1475),
(gen_random_uuid(),'Semantic Ambiguity Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1476),
(gen_random_uuid(),'Narrative Flow Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,1477),
(gen_random_uuid(),'Persuasion Strength Evaluation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1478),
(gen_random_uuid(),'Authority Signal Detection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1479),
(gen_random_uuid(),'Trust Signal Evaluation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,1480),
(gen_random_uuid(),'Impact Score Calculation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1481),
(gen_random_uuid(),'MMS 1 — Tone of Voice Audit System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1482),
(gen_random_uuid(),'Emotional Signal Mapping','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1483),
(gen_random_uuid(),'Audience Fit Detection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1484),
(gen_random_uuid(),'MMS 2 — Linguistic Optimization System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1485),
(gen_random_uuid(),'Sentence Complexity Detection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1486),
(gen_random_uuid(),'Redundancy Detection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1487),
(gen_random_uuid(),'Semantic Ambiguity Detection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1488),
(gen_random_uuid(),'Coherence Validation','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1489),
(gen_random_uuid(),'Narrative Flow Mapping','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,1490),
(gen_random_uuid(),'MMS 3 — Custom GPT Voice Training System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1491),
(gen_random_uuid(),'Rhetorical Device Identification','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1492),
(gen_random_uuid(),'Authority Signal Detection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1493),
(gen_random_uuid(),'Narrative Pattern Extraction','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,1494),
(gen_random_uuid(),'Output Validation','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1495),
(gen_random_uuid(),'Tone of Voice Audit System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1496),
(gen_random_uuid(),'Linguistic Optimization System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1497),
(gen_random_uuid(),'Custom GPT Voice Training System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1498),
(gen_random_uuid(),'cognitive_simplification','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1499),
(gen_random_uuid(),'Sentence Simplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1500),
(gen_random_uuid(),'Ambiguity Elimination Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1501),
(gen_random_uuid(),'Value Positioning Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1502),
(gen_random_uuid(),'Curiosity Trigger Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1503),
(gen_random_uuid(),'Proof Injection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,1504),
(gen_random_uuid(),'CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,1505),
(gen_random_uuid(),'name: Decision Activation System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1506),
(gen_random_uuid(),'process: optimization','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1507),
(gen_random_uuid(),'MMS 1 — Market Intelligence System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1508),
(gen_random_uuid(),'Market Segment Analyzer','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1509),
(gen_random_uuid(),'MMS 2 — Demand & Pain Extraction System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1510),
(gen_random_uuid(),'Subsegment Requests Generator','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1511),
(gen_random_uuid(),'Deep Pain Analyzer','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1512),
(gen_random_uuid(),'MMS 3 — Avatar Construction System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1513),
(gen_random_uuid(),'Demographic Profile Builder','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1514),
(gen_random_uuid(),'Interests Mapping','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1515),
(gen_random_uuid(),'MMS 4 — Psychological Profile System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1516),
(gen_random_uuid(),'Fear Extraction','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1517),
(gen_random_uuid(),'Emotional Mapping','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1518),
(gen_random_uuid(),'Objection Detection','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,1519),
(gen_random_uuid(),'Relationship Impact Mapping','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1520),
(gen_random_uuid(),'MMS 5 — Messaging System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1521),
(gen_random_uuid(),'Messaging Angle Generator','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1522),
(gen_random_uuid(),'Narrative Builder','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','narrative',true,1523),
(gen_random_uuid(),'Market Intelligence System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1524),
(gen_random_uuid(),'Demand & Pain Extraction System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1525),
(gen_random_uuid(),'Avatar Construction System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1526),
(gen_random_uuid(),'Psychological Profile System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1527),
(gen_random_uuid(),'Messaging System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1528),
(gen_random_uuid(),'Psychological Intelligence Engine','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1529),
(gen_random_uuid(),'SPECIFICAȚIE TEHNICĂ — STEP BACK SERVICE GENERATION ENGINE','OTOS','general','',50,200,'B','L1','text','system',true,1530),
(gen_random_uuid(),'id: STEP_BACK_SERVICE_GENERATION_ENGINE','OTOS','general','',50,200,'B','L1','text','system',true,1531),
(gen_random_uuid(),'type: meta_generation_system','OTOS','general','',50,200,'B','L1','text','system',true,1532),
(gen_random_uuid(),'3) STEP BACK ENGINE','OTOS','general','',50,200,'B','L1','text','system',true,1533),
(gen_random_uuid(),'3.1 CAUSAL CHAIN EXTRACTION','OTOS','general','',50,200,'B','L1','text','general',true,1534),
(gen_random_uuid(),'3.2 CONTROL POINT DETECTION','OTOS','general','',50,200,'B','L1','text','general',true,1535),
(gen_random_uuid(),'feedback_loop','OTOS','general','',50,200,'B','L1','text','general',true,1536),
(gen_random_uuid(),'7) SCORING ENGINE','OTOS','general','',50,200,'B','L1','text','system',true,1537),
(gen_random_uuid(),'full_operational_system','OTOS','general','',50,200,'B','L1','text','system',true,1538),
(gen_random_uuid(),'risk_detection','OTOS','general','',50,200,'B','L1','text','general',true,1539),
(gen_random_uuid(),'compliance_validation','OTOS','general','',50,200,'B','L1','text','general',true,1540),
(gen_random_uuid(),'Regulation Interpretation Formula','OTOS','general','',50,200,'B','L1','text','general',true,1541),
(gen_random_uuid(),'Risk Detection Formula','OTOS','general','',50,200,'B','L1','text','general',true,1542),
(gen_random_uuid(),'Compliance Validation Formula','OTOS','general','',50,200,'B','L1','text','general',true,1543),
(gen_random_uuid(),'Compliance Audit System','OTOS','general','',50,200,'B','L1','text','system',true,1544),
(gen_random_uuid(),'Emotion Trigger Formula','OTOS','general','',50,200,'B','L1','text','general',true,1545),
(gen_random_uuid(),'Objection Handling Formula','OTOS','general','',50,200,'B','L1','text','objections',true,1546),
(gen_random_uuid(),'Pressure Build Formula','OTOS','general','',50,200,'B','L1','text','general',true,1547),
(gen_random_uuid(),'Clarity Line Formula','OTOS','general','',50,200,'B','L1','text','general',true,1548),
(gen_random_uuid(),'Emotion + Clarity + CTA → Conversion Message System','OTOS','general','',50,200,'B','L1','text','cta',true,1549),
(gen_random_uuid(),'Lead System + Conversion System + Retention System','OTOS','general','',50,200,'B','L1','text','system',true,1550),
(gen_random_uuid(),'👉 asta e Behavioral Engine','OTOS','general','',50,200,'B','L1','text','system',true,1551),
(gen_random_uuid(),'Clarity Formula','OTOS','general','',50,200,'B','L1','text','general',true,1552),
(gen_random_uuid(),'Trust Signal Formula','OTOS','general','',50,200,'B','L1','text','trust',true,1553),
(gen_random_uuid(),'Conversion System','OTOS','general','',50,200,'B','L1','text','system',true,1554),
(gen_random_uuid(),'causal_chain_generator','OTOS','general','',50,200,'B','L1','text','general',true,1555),
(gen_random_uuid(),'mechanism_generator','OTOS','general','',50,200,'B','L1','text','general',true,1556),
(gen_random_uuid(),'otos_generator','OTOS','general','',50,200,'B','L1','text','general',true,1557),
(gen_random_uuid(),'5) SCORING','OTOS','general','',50,200,'B','L1','text','general',true,1558),
(gen_random_uuid(),'Behavioral Engine','OTOS','general','',50,200,'B','L1','text','system',true,1559),
(gen_random_uuid(),'Mechanism Generator + Scoring Engine','OTOS','general','',50,200,'B','L1','text','system',true,1560),
(gen_random_uuid(),'Inbound Lead Lift System','OTOS','general','',50,200,'B','L1','text','system',true,1561),
(gen_random_uuid(),'Conversion Rate Lift System','OTOS','general','',50,200,'B','L1','text','system',true,1562),
(gen_random_uuid(),'Authority Halo Lift Sequence','OTOS','general','',50,200,'B','L1','text','email',true,1563)
ON CONFLICT DO NOTHING;