-- Seed service registry with all 1490 services from uploaded files
-- Using TRUNCATE + INSERT for clean slate

TRUNCATE service_registry;

-- Insert first batch (services 1-100)
INSERT INTO service_registry (id,name,service_level,category,intent,neurons_cost_min,neurons_cost_max,score_tier,complexity,output_type,domain,is_active,position) VALUES
('curiosity-gap-hook-formula','Curiosity Gap Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,1),
('contrarian-claim-hook-formula','Contrarian Claim Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,2),
('pain-amplification-hook-formula','Pain Amplification Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,3),
('brutal-truth-hook-formula','Brutal Truth Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,4),
('specificity-shock-hook-formula','Specificity Shock Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,5),
('timeline-disruption-hook-formula','Timeline Disruption Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,6),
('identity-attack-hook-formula','Identity Attack Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,7),
('pattern-interrupt-hook-formula','Pattern Interrupt Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,8),
('reverse-promise-hook-formula','Reverse Promise Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,9),
('hidden-mechanism-reveal-hook-formula','Hidden Mechanism Reveal Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,10),
('binary-choice-hook-formula','Binary Choice Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,11),
('myth-destruction-hook-formula','Myth Destruction Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,12),
('outcome-snapshot-hook-formula','Outcome Snapshot Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,13),
('beforeafter-collapse-hook-formula','Before/After Collapse Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,14),
('authority-undermining-hook-formula','Authority Undermining Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,15),
('data-shock-hook-formula','Data Shock Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,16),
('micro-story-hook-formula','Micro-Story Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,17),
('question-reversal-hook-formula','Question Reversal Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,18),
('enemy-framing-hook-formula','Enemy Framing Hook Formula','OTOS','HOOK / OPENING FORMULAS','HOOK / OPENING FORMULAS',20,80,'B','L1','text','hooks',true,19),
('single-step-command-cta-formula','Single-Step Command CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,20),
('urgency-compression-cta-formula','Urgency Compression CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,21),
('risk-reversal-cta-formula','Risk Reversal CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,22),
('outcome-lock-cta-formula','Outcome Lock CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,23),
('identity-upgrade-cta-formula','Identity Upgrade CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,24),
('scarcity-countdown-cta-formula','Scarcity Countdown CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,25),
('direct-imperative-cta-formula','Direct Imperative CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,26),
('micro-commitment-cta-formula','Micro-Commitment CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,27),
('curiosity-loop-cta-formula','Curiosity Loop CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,28),
('authority-transfer-cta-formula','Authority Transfer CTA Formula','OTOS','CTA FORMULAS','CTA FORMULAS',20,80,'B','L1','text','cta',true,29),
('stack-value-amplification-formula','Stack Value Amplification Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,30),
('price-anchoring-formula','Price Anchoring Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,31),
('bonus-justification-formula','Bonus Justification Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,32),
('loss-aversion-offer-formula','Loss Aversion Offer Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,33),
('outcome-guarantee-formula','Outcome Guarantee Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,34),
('time-compression-offer-formula','Time Compression Offer Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,35),
('transformation-framing-formula','Transformation Framing Formula','OTOS','OFFER / VALUE FORMULAS','OFFER / VALUE FORMULAS',20,80,'B','L1','text','offers',true,36),
('origin-transformation-formula','Origin Transformation Formula','OTOS','STORY / NARRATIVE FORMULAS','STORY / NARRATIVE FORMULAS',20,80,'B','L1','text','narrative',true,37),
('authority-signal-formula','Authority Signal Formula','OTOS','PSYCHOLOGICAL TRIGGERS','PSYCHOLOGICAL TRIGGERS',20,80,'B','L1','text','psychology',true,38),
('social-proof-compression-formula','Social Proof Compression Formula','OTOS','PSYCHOLOGICAL TRIGGERS','PSYCHOLOGICAL TRIGGERS',20,80,'B','L1','text','psychology',true,39),
('authority-claim-formula','Authority Claim Formula','OTOS','PERSONAL BRAND SIGNALS','PERSONAL BRAND SIGNALS',20,80,'B','L1','text','branding',true,40),
('expertise-compression-formula','Expertise Compression Formula','OTOS','PERSONAL BRAND SIGNALS','PERSONAL BRAND SIGNALS',20,80,'B','L1','text','branding',true,41),
('identity-positioning-line-formula','Identity Positioning Line Formula','OTOS','PERSONAL BRAND SIGNALS','PERSONAL BRAND SIGNALS',20,80,'B','L1','text','branding',true,42),
('unique-mechanism-naming-formula','Unique Mechanism Naming Formula','OTOS','PERSONAL BRAND SIGNALS','PERSONAL BRAND SIGNALS',20,80,'B','L1','text','branding',true,43),
('button-text-optimization-formula','Button Text Optimization Formula','OTOS','MICRO-CONVERSION ELEMENTS','MICRO-CONVERSION ELEMENTS',20,80,'B','L1','text','ux',true,44),
('form-field-reduction-formula','Form Field Reduction Formula','OTOS','MICRO-CONVERSION ELEMENTS','MICRO-CONVERSION ELEMENTS',20,80,'B','L1','text','ux',true,45),
('execution-loop-definition-formula','Execution Loop Definition Formula','OTOS','AI / AUTOMATION','AI / AUTOMATION',20,80,'B','L1','text','automation',true,46),
('system-dependency-mapping-formula','System Dependency Mapping Formula','OTOS','AI / AUTOMATION','AI / AUTOMATION',20,80,'B','L1','text','automation',true,47),
('content-topic-extraction-formula','Content Topic Extraction Formula','OTOS','CONTENT SYSTEM','CONTENT SYSTEM',20,80,'B','L1','text','content',true,48),
('audience-segmentation-formula','Audience Segmentation Formula','OTOS','AUDIENCE / MARKET','AUDIENCE / MARKET',20,80,'B','L1','text','market',true,49),
('pain-point-isolation-formula','Pain Point Isolation Formula','OTOS','AUDIENCE / MARKET','AUDIENCE / MARKET',20,80,'B','L1','text','market',true,50),
('identity-core-extraction-formula','Identity Core Extraction Formula','OTOS','PERSONAL BRAND / POSITIONING','PERSONAL BRAND / POSITIONING',20,80,'B','L1','text','branding',true,51),
('task-prioritization-formula','Task Prioritization Formula','OTOS','EXECUTION / PRODUCTIVITY','EXECUTION / PRODUCTIVITY',20,80,'B','L1','text','product',true,52),
('lead-qualification-formula','Lead Qualification Formula','OTOS','SALES / CONVERSION','SALES / CONVERSION',20,80,'B','L1','text','sales',true,53),
('closing-path-selection-formula','Closing Path Selection Formula','OTOS','SALES / CONVERSION','SALES / CONVERSION',20,80,'B','L1','text','sales',true,54),
('entry-point-optimization-formula','Entry Point Optimization Formula','OTOS','FUNNEL / USER FLOW','FUNNEL / USER FLOW',20,80,'B','L1','text','funnels',true,55),
('funnel-simplification-formula','Funnel Simplification Formula','OTOS','FUNNEL / USER FLOW','FUNNEL / USER FLOW',20,80,'B','L1','text','funnels',true,56),
('channel-selection-formula','Channel Selection Formula','OTOS','GROWTH / DISTRIBUTION','GROWTH / DISTRIBUTION',20,80,'B','L1','text','growth',true,57),
('community-entry-filter-formula','Community Entry Filter Formula','OTOS','COMMUNITY / NETWORK','COMMUNITY / NETWORK',20,80,'B','L1','text','community',true,58),
('competitor-position-mapping-formula','Competitor Position Mapping Formula','OTOS','MARKET / COMPETITION','MARKET / COMPETITION',20,80,'B','L1','text','market',true,59),
('knowledge-compression-formula','Knowledge Compression Formula','OTOS','LEARNING / KNOWLEDGE','LEARNING / KNOWLEDGE',20,80,'B','L1','text','learning',true,60),
('hallucination-detection-formula','Hallucination Detection Formula','OTOS','AI OUTPUT / QUALITY','AI OUTPUT / QUALITY',20,80,'B','L1','text','automation',true,61),
('goal-clarity-formula','Goal Clarity Formula','OTOS','META-DECISION / CONTROL','META-DECISION / CONTROL',20,80,'B','L1','text','strategy',true,62),
('process-standardization-formula','Process Standardization Formula','OTOS','OPERATIONS / EXECUTION','OPERATIONS / EXECUTION',20,80,'B','L1','text','operations',true,63),
('negotiation-leverage-identification-formula','Negotiation Leverage Formula','OTOS','NEGOTIATION / INFLUENCE','NEGOTIATION / INFLUENCE',20,80,'B','L1','text','negotiation',true,64),
('value-tokenization-formula','Value Tokenization Formula','OTOS','TOKENIZATION / DIGITAL','TOKENIZATION / DIGITAL',20,80,'B','L1','text','tokenization',true,65),
('human-ai-task-split-formula','Human-AI Task Split Formula','OTOS','HYBRID HUMAN-AI','HYBRID HUMAN-AI',20,80,'B','L1','text','automation',true,66),
('knowledge-validation-formula','Knowledge Validation Formula','OTOS','EPISTEMIC CONTROL','EPISTEMIC CONTROL',20,80,'B','L1','text','security',true,67),
('attention-capture-formula','Attention Capture Formula','OTOS','ATTENTION ECONOMY','ATTENTION ECONOMY',20,80,'B','L1','text','attention',true,68),
('perceived-value-amplification-formula','Perceived Value Amplification Formula','OTOS','ECONOMIC PSYCHOLOGY','ECONOMIC PSYCHOLOGY',20,80,'B','L1','text','offers',true,69),
('information-hierarchy-definition-formula','Information Hierarchy Formula','OTOS','INFORMATION DESIGN','INFORMATION DESIGN',20,80,'B','L1','text','information',true,70),
('concept-encoding-formula','Concept Encoding Formula','OTOS','LANGUAGE / SYMBOL','LANGUAGE / SYMBOL',20,80,'B','L1','text','linguistic',true,71),
('message-propagation-formula','Message Propagation Formula','OTOS','INFLUENCE / PROPAGATION','INFLUENCE / PROPAGATION',20,80,'B','L1','text','negotiation',true,72),
('belief-disruption-formula','Belief Disruption Formula','OTOS','PERCEPTION / COGNITIVE','PERCEPTION / COGNITIVE',20,80,'B','L1','text','psychology',true,73),
('failure-recovery-formula','Failure Recovery Formula','OTOS','FAILURE / RESILIENCE','FAILURE / RESILIENCE',20,80,'B','L1','text','resilience',true,74),
('time-compression-formula','Time Compression Formula','OTOS','TIME / TEMPORAL','TIME / TEMPORAL',20,80,'B','L1','text','temporal',true,75),
('security-layer-prioritization-formula','Security Layer Formula','OTOS','SECURITY / CONTROL','SECURITY / CONTROL',20,80,'B','L1','text','security',true,76),
('system-component-mapping-formula','System Component Mapping Formula','OTOS','INFRASTRUCTURE','INFRASTRUCTURE',20,80,'B','L1','text','infrastructure',true,77),
('data-source-identification-formula','Data Source Identification Formula','OTOS','DATA ENGINEERING','DATA ENGINEERING',20,80,'B','L1','text','infrastructure',true,78),
('hypothesis-definition-formula','Hypothesis Definition Formula','OTOS','RESEARCH / DISCOVERY','RESEARCH / DISCOVERY',20,80,'B','L1','text','research',true,79),
('micro-concession-formula','Micro-Concession Formula','OTOS','NEGOTIATION MICRO','NEGOTIATION MICRO',20,80,'B','L1','text','negotiation',true,80),
('cold-outreach-conversion-system','Cold Outreach Conversion System','MMS','CLIENT ACQUISITION','CLIENT ACQUISITION',200,800,'A','L2','text','leadgen',true,81),
('click-to-action-acceleration-system','Click-to-Action Acceleration System','MMS','CONVERSION','CONVERSION',200,800,'A','L2','text','sales',true,82),
('subscription-conversion-system','Subscription Conversion System','MMS','CONVERSION','CONVERSION',200,800,'A','L2','text','sales',true,83),
('tone-of-voice-audit-system','Tone of Voice Audit System','MMS','LINGUISTIC CONTROL','LINGUISTIC CONTROL',200,800,'A','L2','text','linguistic',true,84),
('linguistic-optimization-system','Linguistic Optimization System','MMS','LINGUISTIC CONTROL','LINGUISTIC CONTROL',200,800,'A','L2','text','linguistic',true,85),
('custom-gpt-voice-training-system','Custom GPT Voice Training System','MMS','LINGUISTIC CONTROL','LINGUISTIC CONTROL',200,800,'A','L2','text','linguistic',true,86),
('market-intelligence-system','Market Intelligence System','MMS','MARKET','MARKET',200,800,'A','L2','text','market',true,87),
('demand-pain-extraction-system','Demand & Pain Extraction System','MMS','MARKET','MARKET',200,800,'A','L2','text','market',true,88),
('avatar-construction-system','Avatar Construction System','MMS','MARKET','MARKET',200,800,'A','L2','text','market',true,89),
('psychological-profile-system','Psychological Profile System','MMS','PSYCHOLOGY','PSYCHOLOGY',200,800,'A','L2','text','psychology',true,90),
('messaging-system','Messaging System','MMS','MESSAGING','MESSAGING',200,800,'A','L2','text','content',true,91),
('psychological-avatar-os','Psychological Avatar OS','LCSS','AVATAR','AVATAR',1000,5000,'S','L3','text','psychology',true,92),
('psychological-intelligence-engine','Psychological Intelligence Engine','LCSS','INTELLIGENCE','INTELLIGENCE',1000,5000,'S','L3','text','psychology',true,93),
('inbound-lead-lift-system','Inbound Lead Lift System','LCSS','CLIENT ACQUISITION','CLIENT ACQUISITION',1000,5000,'S','L3','text','leadgen',true,94),
('conversion-rate-lift-system','Conversion Rate Lift System','LCSS','CONVERSION','CONVERSION',1000,5000,'S','L3','text','sales',true,95),
('authority-halo-lift-sequence','Authority Halo Lift Sequence','LCSS','BRANDING','BRANDING',1000,5000,'S','L3','text','branding',true,96),
('market-segment-analyzer-prompt','Market Segment Analyzer Prompt','LCSS','MARKET ANALYSIS','MARKET ANALYSIS',1000,5000,'S','L3','text','market',true,97),
('deep-pain-analyzer-prompt','Deep Pain Analyzer Prompt','LCSS','MARKET ANALYSIS','MARKET ANALYSIS',1000,5000,'S','L3','text','market',true,98),
('demographic-profile-builder-prompt','Demographic Profile Builder Prompt','LCSS','MARKET ANALYSIS','MARKET ANALYSIS',1000,5000,'S','L3','text','market',true,99),
('interest-mapping-prompt','Interest Mapping Prompt','LCSS','MARKET ANALYSIS','MARKET ANALYSIS',1000,5000,'S','L3','text','market',true,100),
('messaging-angle-generator-prompt','Messaging Angle Generator Prompt','LCSS','MESSAGING','MESSAGING',1000,5000,'S','L3','text','content',true,101)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,service_level=EXCLUDED.service_level,category=EXCLUDED.category,intent=EXCLUDED.intent,neurons_cost_min=EXCLUDED.neurons_cost_min,neurons_cost_max=EXCLUDED.neurons_cost_max,score_tier=EXCLUDED.score_tier,complexity=EXCLUDED.complexity,domain=EXCLUDED.domain,position=EXCLUDED.position;