
INSERT INTO public.service_units (
  id, name, domain, level, role, intent,
  single_function, single_output, single_decision,
  mechanism, status, version,
  pricing_json, cost_json, score_json
) VALUES
(
  'a0a0a0a0-0001-4000-8000-000000000001',
  'Customer Truth Report™',
  'customer_intelligence',
  'mms',
  'Decision-grade customer intelligence',
  'Complete truth report connecting causes, blocks, and language into a single decision',
  'Full avatar + JTBD + objection + language analysis',
  'Customer Truth Report (25-40 pages)',
  'Go/No-Go on messaging strategy',
  'ai_pipeline_33_modules',
  'active',
  1,
  '{"price_eur": 2400, "credits_required": 2600, "token_equivalent": 2400000, "delivery_sla_hours": 72, "confidence_threshold": 0.7, "category": "CANONICAL", "is_recommended": true, "badge": "Most chosen", "gating": {"requires": [], "unlocks": ["a0a0a0a0-0001-4000-8000-000000000006", "a0a0a0a0-0001-4000-8000-000000000007", "a0a0a0a0-0001-4000-8000-000000000008"]}, "highlights": ["Executive Truth (1 page)", "Avatar Core (fears, shame, desires)", "JTBD Situations Map", "Objection Genome", "Language Guardrails", "Strategic Implications"]}'::jsonb,
  '{"cost_estimate_eur": 70, "gross_margin_percent": 97}'::jsonb,
  '{"payability": 10, "defensibility": 9, "reusability": 10, "compressibility": 8}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000002',
  'Customer Truth Strategic™',
  'customer_intelligence',
  'lcss',
  'Final business decision with human override',
  'Full report + decision call + positioning verdict',
  'Full analysis + human review + Go/No-Go call',
  'Strategic Truth Report + Call + Verdict',
  'Final Go/No-Go on business positioning',
  'ai_pipeline_33_modules_plus_human',
  'active',
  1,
  '{"price_eur": 5000, "credits_required": 5200, "token_equivalent": 5000000, "delivery_sla_hours": 96, "confidence_threshold": 0.8, "category": "STRATEGIC", "includes_human_override": true, "badges": ["High-stakes", "Go/No-Go"], "gating": {"requires": [], "unlocks": ["a0a0a0a0-0001-4000-8000-000000000006", "a0a0a0a0-0001-4000-8000-000000000007", "a0a0a0a0-0001-4000-8000-000000000008"]}, "highlights": ["Full Customer Truth Report™", "Human override & contradiction review", "Go/No-Go verdict", "Positioning recommendations"]}'::jsonb,
  '{"cost_estimate_eur": 120, "gross_margin_percent": 97.5}'::jsonb,
  '{"payability": 10, "defensibility": 10, "reusability": 10, "compressibility": 7}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000003',
  'Avatar Core Snapshot™',
  'customer_intelligence',
  'otos',
  'Psychological snapshot: fears, shame, desires',
  'A psychological snapshot spoken in the client''s language',
  'Core avatar extraction (fears, shame, desires)',
  'Avatar Core Snapshot (1-2 pages)',
  'Initial clarity on who the client really is',
  'ai_pipeline_avatar_core',
  'active',
  1,
  '{"price_eur": 390, "credits_required": 450, "token_equivalent": 390000, "delivery_sla_hours": 48, "confidence_threshold": 0.6, "category": "PROBE", "badges": ["Probe", "Incomplete by design"], "probe_rules": {"is_incomplete_by_design": true, "stacking_allowed": false}, "upgrade_paths": [{"to_service_id": "a0a0a0a0-0001-4000-8000-000000000001", "mode": "PAY_DIFFERENCE", "credit_carry_over_percent": 100, "expires_in_days": 30}], "gap_revelation": {"title": "What this does NOT include", "items": ["JTBD contexts and triggers", "Objection Genome (full)", "Strategic implications"]}, "highlights": ["5 dominant fears", "3 active shame points", "3 real desires", "Raw voice snippets"]}'::jsonb,
  '{"cost_estimate_eur": 60, "gross_margin_percent": 84.6}'::jsonb,
  '{"payability": 8, "defensibility": 7, "reusability": 6, "compressibility": 9}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000004',
  'Objection X-Ray™',
  'customer_intelligence',
  'otos',
  'Real reasons they don''t buy, mapped as language',
  'The real reasons they don''t buy—mapped as language, not theory',
  'Objection extraction with severity scoring',
  'Objection X-Ray (1-2 pages)',
  'Clarity on what blocks the sale',
  'ai_pipeline_objection_genome',
  'active',
  1,
  '{"price_eur": 590, "credits_required": 650, "token_equivalent": 590000, "delivery_sla_hours": 48, "confidence_threshold": 0.6, "category": "PROBE", "badges": ["Probe", "Sales-blocker"], "probe_rules": {"is_incomplete_by_design": true, "stacking_allowed": false}, "upgrade_paths": [{"to_service_id": "a0a0a0a0-0001-4000-8000-000000000001", "mode": "PAY_DIFFERENCE", "credit_carry_over_percent": 100, "expires_in_days": 30}], "gap_revelation": {"title": "What this does NOT include", "items": ["Full Avatar Core", "JTBD purchase contexts", "Language Guardrails (complete)"]}, "highlights": ["7-10 objections (ranked)", "Exact skeptical language", "Risk score per objection", "Triggers that amplify resistance"]}'::jsonb,
  '{"cost_estimate_eur": 60, "gross_margin_percent": 89.8}'::jsonb,
  '{"payability": 9, "defensibility": 8, "reusability": 7, "compressibility": 9}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000005',
  'JTBD Trigger Map™',
  'customer_intelligence',
  'otos',
  'When they buy, why now, what forces the decision',
  'When they buy, why now, and what event forces the decision',
  'JTBD situation extraction with trigger mapping',
  'JTBD Trigger Map (1-2 pages)',
  'Clarity on purchase timing and triggers',
  'ai_pipeline_jtbd_contexts',
  'active',
  1,
  '{"price_eur": 790, "credits_required": 850, "token_equivalent": 790000, "delivery_sla_hours": 48, "confidence_threshold": 0.6, "category": "PROBE", "badges": ["Probe", "Decision-context"], "probe_rules": {"is_incomplete_by_design": true, "stacking_allowed": false}, "upgrade_paths": [{"to_service_id": "a0a0a0a0-0001-4000-8000-000000000001", "mode": "PAY_DIFFERENCE", "credit_carry_over_percent": 100, "expires_in_days": 30}], "gap_revelation": {"title": "What this does NOT include", "items": ["Objection Genome (full)", "Emotional Drivers Matrix", "Strategic implications"]}, "highlights": ["5 JTBD situations", "Trigger event per situation", "Emotional state + rationale", "Why alternatives fail"]}'::jsonb,
  '{"cost_estimate_eur": 60, "gross_margin_percent": 92.4}'::jsonb,
  '{"payability": 9, "defensibility": 8, "reusability": 8, "compressibility": 9}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000006',
  'Funnel Messaging Blueprint™',
  'customer_intelligence',
  'mms',
  'Translate truth into funnel messaging',
  'Translate truth into a funnel: ads → landing → email → close',
  'Funnel messaging mapping from truth report',
  'Funnel Messaging Blueprint (document)',
  'What to say at each funnel stage',
  'ai_pipeline_funnel_messaging',
  'active',
  1,
  '{"price_eur": 1500, "credits_required": 1700, "token_equivalent": 1500000, "delivery_sla_hours": 72, "confidence_threshold": 0.7, "category": "DOWNSTREAM", "badges": ["Locked by default"], "gating": {"requires": ["a0a0a0a0-0001-4000-8000-000000000001"], "allow_if_higher_tier": ["a0a0a0a0-0001-4000-8000-000000000002"], "locked_tooltip": "Run Customer Truth Report™ to unlock."}, "highlights": ["Messaging per funnel stage", "Hook mapping to drivers", "What to say vs what to avoid"]}'::jsonb,
  '{"cost_estimate_eur": 80, "gross_margin_percent": 94.7}'::jsonb,
  '{"payability": 9, "defensibility": 8, "reusability": 9, "compressibility": 8}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000007',
  'Content Angle Engine™',
  'customer_intelligence',
  'mms',
  'Extract validated content angles from truth data',
  'Extract 20-40 angles grounded in drivers and objections',
  'Content angle extraction from truth report',
  'Content Angles List (20-40 angles)',
  'What angles to use in ads/reels/headlines',
  'ai_pipeline_content_angles',
  'active',
  1,
  '{"price_eur": 1200, "credits_required": 1400, "token_equivalent": 1200000, "delivery_sla_hours": 72, "confidence_threshold": 0.7, "category": "DOWNSTREAM", "badges": ["Locked by default"], "gating": {"requires": ["a0a0a0a0-0001-4000-8000-000000000001"], "allow_if_higher_tier": ["a0a0a0a0-0001-4000-8000-000000000002"], "locked_tooltip": "Run Customer Truth Report™ to unlock."}, "highlights": ["Angles for ads/reels/headlines", "Driver anchor per angle", "Avoidance rules"]}'::jsonb,
  '{"cost_estimate_eur": 75, "gross_margin_percent": 93.8}'::jsonb,
  '{"payability": 8, "defensibility": 7, "reusability": 9, "compressibility": 8}'::jsonb
),
(
  'a0a0a0a0-0001-4000-8000-000000000008',
  'Sales Objection Playbook™',
  'customer_intelligence',
  'mms',
  'Objection → response mapping for sales teams',
  'Objection → response mapping for calls and closers. Guardrails included.',
  'Sales objection response generation from truth report',
  'Sales Objection Playbook (document)',
  'How to handle every objection in calls',
  'ai_pipeline_sales_playbook',
  'active',
  1,
  '{"price_eur": 1800, "credits_required": 2100, "token_equivalent": 1800000, "delivery_sla_hours": 72, "confidence_threshold": 0.7, "category": "DOWNSTREAM", "badges": ["Locked by default"], "gating": {"requires": ["a0a0a0a0-0001-4000-8000-000000000001"], "allow_if_higher_tier": ["a0a0a0a0-0001-4000-8000-000000000002"], "locked_tooltip": "Run Customer Truth Report™ to unlock."}, "highlights": ["Response patterns (no fluff)", "Allowed vs forbidden language", "Common failure modes"]}'::jsonb,
  '{"cost_estimate_eur": 90, "gross_margin_percent": 95}'::jsonb,
  '{"payability": 9, "defensibility": 8, "reusability": 8, "compressibility": 8}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  pricing_json = EXCLUDED.pricing_json,
  cost_json = EXCLUDED.cost_json,
  score_json = EXCLUDED.score_json,
  intent = EXCLUDED.intent,
  status = EXCLUDED.status,
  updated_at = now();
