INSERT INTO service_registry (id,name,service_level,category,intent,neurons_cost_min,neurons_cost_max,score_tier,complexity,output_type,domain,is_active,position) VALUES
(gen_random_uuid(),'Creator Revenue Diversification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1001),
(gen_random_uuid(),'Creator Growth Strategy Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1002),
(gen_random_uuid(),'Audience Retention Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1003),
(gen_random_uuid(),'Creator Brand Expansion Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1004),
(gen_random_uuid(),'Content ROI Calculation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1005),
(gen_random_uuid(),'Creator Leverage Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1006),
(gen_random_uuid(),'Input-Output Contract Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1007),
(gen_random_uuid(),'Service Boundary Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1008),
(gen_random_uuid(),'Reusability Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1009),
(gen_random_uuid(),'Interface Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1010),
(gen_random_uuid(),'Dependency Isolation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1011),
(gen_random_uuid(),'Component Interaction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1012),
(gen_random_uuid(),'Service Abstraction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1013),
(gen_random_uuid(),'Integration Simplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1014),
(gen_random_uuid(),'Module Communication Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1015),
(gen_random_uuid(),'Data Exchange Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1016),
(gen_random_uuid(),'Interface Stability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1017),
(gen_random_uuid(),'Component Scalability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1018),
(gen_random_uuid(),'System Plugability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1019),
(gen_random_uuid(),'Service Compatibility Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1020),
(gen_random_uuid(),'Value Tokenization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1021),
(gen_random_uuid(),'Access Control Token Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1022),
(gen_random_uuid(),'Usage Metering Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1023),
(gen_random_uuid(),'Credit Allocation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1024),
(gen_random_uuid(),'Token Pricing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1025),
(gen_random_uuid(),'Consumption Tracking Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1026),
(gen_random_uuid(),'Incentive Token Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1027),
(gen_random_uuid(),'Reward Distribution Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1028),
(gen_random_uuid(),'Scarcity Token Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1029),
(gen_random_uuid(),'Token Flow Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1030),
(gen_random_uuid(),'Value Exchange Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1031),
(gen_random_uuid(),'Token Utility Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1032),
(gen_random_uuid(),'Digital Ownership Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1033),
(gen_random_uuid(),'Token Economy Balance Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1034),
(gen_random_uuid(),'Access Tier Mapping Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1035),
(gen_random_uuid(),'Human-AI Task Split Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1036),
(gen_random_uuid(),'AI Delegation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1037),
(gen_random_uuid(),'Human Override Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1038),
(gen_random_uuid(),'Decision Escalation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1039),
(gen_random_uuid(),'AI Output Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1040),
(gen_random_uuid(),'Human Feedback Injection Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1041),
(gen_random_uuid(),'Task Automation Boundary Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1042),
(gen_random_uuid(),'Human Supervision Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1043),
(gen_random_uuid(),'AI Assistance Optimization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1044),
(gen_random_uuid(),'Hybrid Workflow Definition Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1045),
(gen_random_uuid(),'Execution Responsibility Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1046),
(gen_random_uuid(),'AI Reliability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1047),
(gen_random_uuid(),'Human Intervention Timing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1048),
(gen_random_uuid(),'Task Assignment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1049),
(gen_random_uuid(),'AI-Human Coordination Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1050),
(gen_random_uuid(),'Knowledge Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1051),
(gen_random_uuid(),'Truth Consistency Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1052),
(gen_random_uuid(),'Evidence Prioritization Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1053),
(gen_random_uuid(),'Fact vs Opinion Separation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1054),
(gen_random_uuid(),'Information Credibility Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1055),
(gen_random_uuid(),'Source Reliability Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1056),
(gen_random_uuid(),'Claim Verification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1057),
(gen_random_uuid(),'Truth Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1058),
(gen_random_uuid(),'Knowledge Conflict Resolution Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1059),
(gen_random_uuid(),'Belief Validation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1060),
(gen_random_uuid(),'Information Integrity Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1061),
(gen_random_uuid(),'Epistemic Boundary Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1062),
(gen_random_uuid(),'Certainty Assessment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1063),
(gen_random_uuid(),'Knowledge Filtering Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1064),
(gen_random_uuid(),'Truth Signal Amplification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1065),
(gen_random_uuid(),'Micro-Concession Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1066),
(gen_random_uuid(),'Position Adjustment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1067),
(gen_random_uuid(),'Counter-Offer Structuring Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1068),
(gen_random_uuid(),'Negotiation Pause Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1069),
(gen_random_uuid(),'Pressure Timing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1070),
(gen_random_uuid(),'Offer Reframing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1071),
(gen_random_uuid(),'Value Rebalancing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1072),
(gen_random_uuid(),'Tension Control Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1073),
(gen_random_uuid(),'Silence Leverage Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1074),
(gen_random_uuid(),'Agreement Acceleration Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1075),
(gen_random_uuid(),'Negotiation Momentum Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1076),
(gen_random_uuid(),'Position Reinforcement Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1077),
(gen_random_uuid(),'Anchor Adjustment Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1078),
(gen_random_uuid(),'Resistance Micro-Break Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,1079),
(gen_random_uuid(),'Deal Closure Signal Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1080),
(gen_random_uuid(),'Hover Feedback Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1081),
(gen_random_uuid(),'Click Confirmation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1082),
(gen_random_uuid(),'Micro-Delay Response Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1083),
(gen_random_uuid(),'Interaction Reinforcement Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1084),
(gen_random_uuid(),'Completion Signal Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1085),
(gen_random_uuid(),'Error Notification Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1086),
(gen_random_uuid(),'Success Confirmation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1087),
(gen_random_uuid(),'Progress Feedback Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1088),
(gen_random_uuid(),'Micro-Animation Trigger Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1089),
(gen_random_uuid(),'Interaction Satisfaction Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1090),
(gen_random_uuid(),'Feedback Timing Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1091),
(gen_random_uuid(),'Action Confirmation Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1092),
(gen_random_uuid(),'Feedback Clarity Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1093),
(gen_random_uuid(),'validation','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1094),
(gen_random_uuid(),'MODEL SCORING','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1095),
(gen_random_uuid(),'6) ECONOMIC LOOP','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1096),
(gen_random_uuid(),'hook_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,1097),
(gen_random_uuid(),'headline_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,1098),
(gen_random_uuid(),'problem_definition_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1099),
(gen_random_uuid(),'value_proposition_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1100),
(gen_random_uuid(),'unique_mechanism_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1101),
(gen_random_uuid(),'objection_handling_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,1102),
(gen_random_uuid(),'guarantee_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1103),
(gen_random_uuid(),'cta_formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,1104),
(gen_random_uuid(),'MMS: Conversion Lift Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1105),
(gen_random_uuid(),'name: Curiosity Gap Hook Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,1106),
(gen_random_uuid(),'name: “Why You Fail at X” Headline Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','headlines',true,1107),
(gen_random_uuid(),'name: Value Proposition Compression Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1108),
(gen_random_uuid(),'name: “I Tried Before” Reframe Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1109),
(gen_random_uuid(),'name: Risk Reversal Guarantee Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1110),
(gen_random_uuid(),'name: Direct Imperative CTA Formula','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','cta',true,1111),
(gen_random_uuid(),'type: validation','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1112),
(gen_random_uuid(),'Client Attraction Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1113),
(gen_random_uuid(),'Lead Capture Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1114),
(gen_random_uuid(),'Inbound Interest Activation Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1115),
(gen_random_uuid(),'Audience → Lead Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1116),
(gen_random_uuid(),'Cold Attention → Warm Lead Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','hooks',true,1117),
(gen_random_uuid(),'Traffic → Qualified Lead System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1118),
(gen_random_uuid(),'Offer Discovery Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1119),
(gen_random_uuid(),'Lead Magnet Deployment System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1120),
(gen_random_uuid(),'Intent Capture Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1121),
(gen_random_uuid(),'First Contact Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1122),
(gen_random_uuid(),'Conversion Lift Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1123),
(gen_random_uuid(),'Landing Message Optimization System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1124),
(gen_random_uuid(),'Offer Clarity Conversion Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1125),
(gen_random_uuid(),'Decision Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1126),
(gen_random_uuid(),'Objection Elimination Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','objections',true,1127),
(gen_random_uuid(),'Trust → Action Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','trust',true,1128),
(gen_random_uuid(),'Lead → Buyer Transition Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1129),
(gen_random_uuid(),'Conversion Path Compression System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1130),
(gen_random_uuid(),'High-Intent Conversion Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1131),
(gen_random_uuid(),'Offer Acceptance Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1132),
(gen_random_uuid(),'Simple Funnel Deployment Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1133),
(gen_random_uuid(),'Multi-Step Funnel System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1134),
(gen_random_uuid(),'Offer Funnel Structuring System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1135),
(gen_random_uuid(),'Entry → Conversion Funnel Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1136),
(gen_random_uuid(),'Funnel Simplification System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1137),
(gen_random_uuid(),'Funnel Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1138),
(gen_random_uuid(),'Funnel Completion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1139),
(gen_random_uuid(),'Lead Journey Funnel System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1140),
(gen_random_uuid(),'Funnel Flow Alignment System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1141),
(gen_random_uuid(),'Conversion Funnel Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1142),
(gen_random_uuid(),'Content Production Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1143),
(gen_random_uuid(),'Content → Lead System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1144),
(gen_random_uuid(),'Content Distribution Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1145),
(gen_random_uuid(),'Content Repurposing System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1146),
(gen_random_uuid(),'Content Consistency Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1147),
(gen_random_uuid(),'Content Authority System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1148),
(gen_random_uuid(),'Content Engagement Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1149),
(gen_random_uuid(),'Content Expansion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1150),
(gen_random_uuid(),'Content Signal Amplification System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1151),
(gen_random_uuid(),'Content → Conversion Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1152),
(gen_random_uuid(),'Offer Structuring Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1153),
(gen_random_uuid(),'Offer Clarity System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1154),
(gen_random_uuid(),'Offer Positioning Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1155),
(gen_random_uuid(),'Offer Differentiation System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1156),
(gen_random_uuid(),'Offer Value Amplification Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1157),
(gen_random_uuid(),'Offer Simplification System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1158),
(gen_random_uuid(),'Offer Launch Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1159),
(gen_random_uuid(),'Offer Validation System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1160),
(gen_random_uuid(),'Offer Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1161),
(gen_random_uuid(),'Offer Conversion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1162),
(gen_random_uuid(),'Authority Positioning Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1163),
(gen_random_uuid(),'Personal Brand Structuring System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1164),
(gen_random_uuid(),'Identity → Authority Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1165),
(gen_random_uuid(),'Expert Positioning System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1166),
(gen_random_uuid(),'Personal Brand Clarity Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1167),
(gen_random_uuid(),'Reputation Building System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1168),
(gen_random_uuid(),'Visibility Expansion Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1169),
(gen_random_uuid(),'Authority Signal System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1170),
(gen_random_uuid(),'Brand Consistency Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1171),
(gen_random_uuid(),'Influence Growth System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1172),
(gen_random_uuid(),'Sales Message System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','sales',true,1173),
(gen_random_uuid(),'Sales Conversion Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1174),
(gen_random_uuid(),'Lead Qualification System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1175),
(gen_random_uuid(),'Closing Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1176),
(gen_random_uuid(),'Sales Flow System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','sales',true,1177),
(gen_random_uuid(),'Sales Friction Reduction Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1178),
(gen_random_uuid(),'Deal Acceleration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1179),
(gen_random_uuid(),'Sales Positioning Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1180),
(gen_random_uuid(),'Buyer Decision System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1181),
(gen_random_uuid(),'Sales Consistency System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','sales',true,1182),
(gen_random_uuid(),'Product Structuring Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1183),
(gen_random_uuid(),'Product Clarity System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1184),
(gen_random_uuid(),'Business Model Alignment Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1185),
(gen_random_uuid(),'Revenue Structuring System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1186),
(gen_random_uuid(),'Product Simplification Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1187),
(gen_random_uuid(),'Product → Offer System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','offers',true,1188),
(gen_random_uuid(),'Business Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1189),
(gen_random_uuid(),'Revenue Expansion System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1190),
(gen_random_uuid(),'Product Positioning Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1191),
(gen_random_uuid(),'Business Clarity System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1192),
(gen_random_uuid(),'AI Workflow Setup Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1193),
(gen_random_uuid(),'Task Automation System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1194),
(gen_random_uuid(),'AI Output Optimization Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1195),
(gen_random_uuid(),'AI Integration System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1196),
(gen_random_uuid(),'Automation Flow Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1197),
(gen_random_uuid(),'AI Execution System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1198),
(gen_random_uuid(),'AI Process Structuring Sequence','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','email',true,1199),
(gen_random_uuid(),'AI Efficiency System','OTOS','PERSONAL BRAND SIGNALS (POSITIONING)','',50,200,'B','L1','text','brand',true,1200)
ON CONFLICT DO NOTHING;