INSERT INTO public.service_catalog (service_key, name, description, credits_cost, category, is_active) VALUES
('product-roadmap', 'Product Roadmap', 'Strategic product roadmap with quarterly goals, feature prioritization, and OKRs', 65, 'strategy', true),
('linkedin-content-calendar', 'LinkedIn Content Calendar', '30-day LinkedIn posting plan with hooks, carousels, and engagement tactics', 50, 'content', true),
('pitch-deck', 'Pitch Deck Script', 'Complete 12-slide pitch deck narrative with speaker notes and investor Q&A prep', 70, 'document', true),
('brand-guidelines', 'Brand Guidelines', 'Full brand identity document: voice, tone, colors, typography, do/don''t examples', 60, 'content', true),
('sales-battlecard', 'Sales Battlecard', 'Competitive sales enablement card with objections, differentiators, and win themes', 55, 'strategy', true),
('user-research-plan', 'User Research Plan', 'Complete UX research plan with interview scripts, survey templates, and analysis framework', 60, 'analysis', true),
('okr-framework', 'OKR Framework', 'Company-wide OKR cascade with team objectives, key results, and tracking dashboard', 55, 'strategy', true),
('podcast-guest-prep', 'Podcast Guest Prep', 'Guest appearance prep kit with talking points, stories, and call-to-action scripts', 40, 'content', true),
('technical-spec', 'Technical Specification', 'Detailed technical specification document with architecture, APIs, and data models', 65, 'document', true),
('social-proof-kit', 'Social Proof Kit', 'Testimonial templates, case study frameworks, and social proof placement strategy', 45, 'content', true),
('meeting-playbook', 'Meeting Playbook', 'Templates for 10 meeting types with agendas, facilitation guides, and follow-up scripts', 40, 'document', true),
('value-proposition-canvas', 'Value Proposition Canvas', 'Complete value prop analysis with customer jobs, pains, gains, and product fit mapping', 55, 'strategy', true),
('email-nurture-sequence', 'Email Nurture Sequence', '12-email nurture sequence with segmentation rules, timing, and A/B test variants', 60, 'content', true),
('competitive-intelligence', 'Competitive Intelligence Report', 'Deep competitive analysis with SWOT, feature comparison, and strategic recommendations', 65, 'analysis', true),
('hiring-playbook', 'Hiring Playbook', 'Complete recruitment guide with job descriptions, interview scorecards, and offer templates', 60, 'document', true),
('product-hunt-launch', 'Product Hunt Launch Kit', 'Full PH launch plan: tagline, description, first comment, hunter outreach, and timeline', 50, 'strategy', true),
('retention-analysis', 'Retention Analysis Framework', 'Churn analysis framework with cohort templates, exit survey design, and win-back flows', 60, 'analysis', true),
('thought-piece', 'Thought Piece Generator', 'Long-form thought leadership article with contrarian angle, data points, and CTA', 45, 'content', true),
('workshop-facilitator', 'Workshop Facilitator Kit', 'Complete workshop package: exercises, timebox, materials list, and participant workbook', 55, 'document', true),
('api-go-to-market', 'API Go-to-Market', 'Developer-focused GTM strategy with documentation, SDK plan, and developer relations', 65, 'strategy', true),
('customer-health-score', 'Customer Health Score', 'Health scoring model with leading indicators, alert thresholds, and playbooks per segment', 60, 'analysis', true),
('content-pillar-strategy', 'Content Pillar Strategy', 'SEO content pillar architecture with topic clusters, internal linking, and editorial calendar', 55, 'strategy', true),
('partnership-playbook', 'Partnership Playbook', 'Strategic partnership framework with evaluation criteria, deal structure, and co-marketing plan', 60, 'strategy', true),
('financial-model', 'Financial Model Narrative', 'Financial model narrative with assumptions, scenarios, unit economics, and investor-ready summary', 70, 'report', true),
('launch-retrospective', 'Launch Retrospective', 'Post-launch analysis framework with metrics review, learnings, and next iteration plan', 45, 'analysis', true)
ON CONFLICT (service_key) DO NOTHING;